### ISSUE TITLE
QGIS server is not working with layers coming from the database

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-qgis-server#11]
# Problem
I have my compose file setup 
```
postgres:
  image: kartoza/postgis:9.5-2.2
  ports:
    - "35432:5432"
  environment:
    - USERNAME=docker
    - PASS=docker
qgisserver:
  image: kartoza/qgis-server:2.18.10
  hostname: qgis-server
  volumes:
    - ./web:/web
  environment:
    - QGIS_PROJECT_FILE=/web/project/project.qgs
    - PGSERVICEFILE=/web/project/pg_service.conf
  links:
    - postgres:postgres
  ports:
    - "30003:80"

```
When I log into the qgis-server container I can connect to the Postgres container by using the service file. `psql service=gis` but when I do a get capabilities on my layer the request generated is not valid. 
![get](https://user-images.githubusercontent.com/2510900/29215527-9bf128d2-7eab-11e7-9a7b-97eadc417a90.png)

I then proceed to open the project file and replace my data source with a shapefile and do a get capabilities which returns true.

I think QGIS server is not connecting properly to the Postgres container.
