### ISSUE TITLE
Service unknown or unsupported

### ISSUE THREAD

**Issue by andreaordonselli** [kartoza/docker-qgis-server#29]
Hi to all,

I have this .yml
```
services:
  db:
    image: kartoza/postgis:9.6-2.4
    environment:
      - USERNAME=docker
      - PASS=docker

  qgisserver:
    image: kartoza/qgis-server:LTR
    hostname: qgis-server
    volumes:
      # Wherever you want to mount your data from
      - ./project:/project
    links:
      - db:db
    ports:
      - "8080:80"
```
I run `docker compose up -d` and all is ok

I have this structure:

```
| qgis-server |
     docker-compose.yml
     | project |
          test.qgs
          | layer |
               lake.shp
```

But when I call `http://localhost:8080/` i've got:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
<ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException>
</ServiceExceptionReport>
```
And if I call `http://localhost:8080/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&MAP=/project/test.qgs` i've got:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
<ServiceException code="WMS configuration error">There was an error reading the project file or the SLD configuration</ServiceException>
</ServiceExceptionReport>
```
What can I do?
Thanks

[project.zip](https://github.com/user-attachments/files/20580620/project.zip)
